name: Create App Signing Key

on:
  workflow_dispatch:

jobs:
  create-keystore:
    runs-on: ubuntu-latest

    steps:
      - name: Create keystore
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: |
          keytool -genkeypair \
            -v \
            -keystore app-release-key.jks \
            -alias shahedltrbah \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass "$KEYSTORE_PASSWORD" \
            -keypass "$KEYSTORE_PASSWORD" \
            -dname "CN=Shahed Ltrbah, OU=App, O=Shahed Ltrbah, L=Algeria, ST=Boumerdes, C=DZ"

      - name: Upload signing key
        uses: actions/upload-artifact@v4
        with:
          name: shahed-signing-key
          path: app-release-key.jks
